services:

  nginx:
    image: nginx:latest
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:9001:9003
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./logs/nginx:/var/log/nginx
    links:
      - php-fpm

  php-fpm:
    build:
      context: docker/php-fpm
    ports:
    - 127.0.0.1:9001:9003
    volumes:
      - ./app:/var/www/html
      - ../wisk-test:/app
      - ./docker/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    environment:
      PHP_IDE_CONFIG: "serverName=PhpServerDev"
    extra_hosts:
      - "php-dev.local www.php-dev.local:127.0.0.1"
    links:
      - "mariadb:db"

  mariadb:
    image: mariadb:10.10
    ports:
    - 127.0.0.1:3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: testdb
      MARIADB_USER: test_user
      MARIADB_PASSWORD: test_pwd
    volumes:
    - ./databases/mariadb:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
    - 127.0.0.1:8080:80
    links:
      - "mariadb:db"
    environment:
      PMA_HOST: mariadb
      PMA_USER: test_user
      PMA_PASSWORD: test_pwd